config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pears#random"

  resources :pears do
    collection do
      get :random
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pear.rb
class Pear < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pears_controller.rb
class PearsController < ApplicationController
  before_action :set_pear, only: %i[ show edit update destroy ]

  PEARS = %w[
    https://snaped.fns.usda.gov/sites/default/files/seasonal-produce/2018-05/pears.jpg
    https://www.tastingtable.com/img/gallery/why-you-should-leave-the-skin-on-pears/l-intro-1653326060.jpg
    https://cdn.tasteatlas.com/images/ingredients/60eea3493ed944f7a4e6db7ff9b4765f.jpg
    http://cdn.shopify.com/s/files/1/2336/3219/products/shutterstock_1693201075_1024x1024.png?v=1621966032
    https://www.halegroves.com/images/xl/906-comice-pears_02.jpg
    https://mnhardy.umn.edu/sites/mnhardy.umn.edu/files/styles/folwell_full/public/2022-08/pears-banner.jpg?itok=7MMHsEhg
    https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2Farchive%2F45c348aabe206cafa9bd7361d9c0df5331f2f746
  ]

  def random
    @pear = Pear.all.sample
  end

  # GET /pears or /pears.json
  def index
    @pears = Pear.all
  end

  # GET /pears/1 or /pears/1.json
  def show
  end

  # GET /pears/new
  def new
    @pear = Pear.new
  end

  # GET /pears/1/edit
  def edit
  end

  # POST /pears or /pears.json
  def create
    @pear = Pear.new(pear_params)

    respond_to do |format|
      if @pear.save
        format.html { redirect_to pear_url(@pear), notice: "Pear was successfully created." }
        format.json { render :show, status: :created, location: @pear }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pears/1 or /pears/1.json
  def update
    respond_to do |format|
      if @pear.update(pear_params)
        format.html { redirect_to pear_url(@pear), notice: "Pear was successfully updated." }
        format.json { render :show, status: :ok, location: @pear }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pears/1 or /pears/1.json
  def destroy
    @pear.destroy

    respond_to do |format|
      format.html { redirect_to pears_url, notice: "Pear was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pear
      @pear = Pear.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pear_params
      params.require(:pear).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pears_helper.rb
module PearsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pears</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <style type="text/css">
    body {
      margin: 2rem;
    }

    h1 {
      font-size: 5rem;
    }

    img {
      max-width: 1000px;
    }
    </style>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pears/_form.html.erb
<%= form_with(model: pear) do |form| %>
  <% if pear.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pear.errors.count, "error") %> prohibited this pear from being saved:</h2>

      <ul>
        <% pear.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pears/_pear.html.erb
<div id="<%= dom_id pear %>">
  <p>
    <strong>Url:</strong>
    <%= pear.url %>
  </p>

</div>

app/views/pears/edit.html.erb
<h1>Editing pear</h1>

<%= render "form", pear: @pear %>

<br>

<div>
  <%= link_to "Show this pear", @pear %> |
  <%= link_to "Back to pears", pears_path %>
</div>

app/views/pears/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pears</h1>

<div id="pears">
  <% @pears.each do |pear| %>
    <img width="300" src="<%= pear.url %>" />

    <p>
      <%= link_to "Show this pear", pear %>
    </p>
  <% end %>
</div>

<%= link_to "New pear", new_pear_path %>

app/views/pears/new.html.erb
<h1>New pear</h1>

<%= render "form", pear: @pear %>

<br>

<div>
  <%= link_to "Back to pears", pears_path %>
</div>

app/views/pears/random.html.erb
<% if @pear %>
  <h1>I'm a pear!</h1>

  <img src="<%= @pear.url %>" />
<% else %>
  <h1>Add a pear!</h1>

  <a href="<%= new_pear_path %>">CLICK HERE TODAY!</a>
<% end %>

app/views/pears/show.html.erb
<p style="color: green"><%= notice %></p>

<img src="<%= @pear.url %>" />

<div>
  <%= link_to "Edit this pear", edit_pear_path(@pear) %> |
  <%= link_to "Back to pears", pears_path %>

  <%= button_to "Destroy this pear", @pear, method: :delete %>
</div>